language: c

os:
    - linux
    - osx

env:
    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.3
        - PYTHON_VERSION=3.4
        - PYTHON_VERSION=3.5
    global:
        - CONDA_DEPENDENCIES='numpy matplotlib psutil'
        - PIP_DEPENDENCIES='coveralls pytest-cov'
        - SETUP_XVFB=True

before_install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - py.test --cov psrecord

after_success:
    - coveralls
